# TCL File Generated by Component Editor 13.0sp1
# Mon Aug 26 18:01:34 PDT 2013
# DO NOT MODIFY


# 
# xcvr_st_converter "xcvr_st_converter" v1.0
#  2013.08.26.18:01:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module xcvr_st_converter
# 
set_module_property DESCRIPTION ""
set_module_property NAME xcvr_st_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME xcvr_st_converter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property GROUP Devkit_IPs


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL xcvr_st_converter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file xcvr_st_converter.v VERILOG PATH xcvr_st_converter.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL xcvr_st_converter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file xcvr_st_converter.v VERILOG PATH xcvr_st_converter.v


# 
# parameters
# 
add_parameter DATAWIDTH INTEGER 40
set_parameter_property DATAWIDTH DEFAULT_VALUE 40
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter NUM_OF_CH INTEGER 1
set_parameter_property NUM_OF_CH DEFAULT_VALUE 1
set_parameter_property NUM_OF_CH DISPLAY_NAME NUM_OF_CH
set_parameter_property NUM_OF_CH TYPE INTEGER
set_parameter_property NUM_OF_CH UNITS None
set_parameter_property NUM_OF_CH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_OF_CH HDL_PARAMETER true


# 
# display items
# 

# 
# connection point tx_parallel_data
# 
add_interface tx_parallel_data conduit end
set_interface_property tx_parallel_data associatedClock ""
set_interface_property tx_parallel_data associatedReset ""
set_interface_property tx_parallel_data ENABLED true
set_interface_property tx_parallel_data EXPORT_OF ""
set_interface_property tx_parallel_data PORT_NAME_MAP ""
set_interface_property tx_parallel_data SVD_ADDRESS_GROUP ""

add_interface_port tx_parallel_data tx_parallel_data tx_parallel_data Output DATAWIDTH*NUM_OF_CH


# 
# connection point tx_clkout
#
add_interface tx_clkout clock end
set_interface_property tx_clkout clockRate 0
set_interface_property tx_clkout ENABLED true
set_interface_property tx_clkout EXPORT_OF ""
set_interface_property tx_clkout PORT_NAME_MAP ""
set_interface_property tx_clkout SVD_ADDRESS_GROUP ""

add_interface_port tx_clkout tx_clkout clk Input NUM_OF_CH



# 
# connection point rx_parallel_data
# 
add_interface rx_parallel_data conduit end
set_interface_property rx_parallel_data associatedClock ""
set_interface_property rx_parallel_data associatedReset ""
set_interface_property rx_parallel_data ENABLED true
set_interface_property rx_parallel_data EXPORT_OF ""
set_interface_property rx_parallel_data PORT_NAME_MAP ""
set_interface_property rx_parallel_data SVD_ADDRESS_GROUP ""

add_interface_port rx_parallel_data rx_parallel_data rx_parallel_data Input DATAWIDTH*NUM_OF_CH

# 
# connection point rx_clkout
# 
add_interface rx_clkout clock end
set_interface_property rx_clkout clockRate 0
set_interface_property rx_clkout ENABLED true
set_interface_property rx_clkout EXPORT_OF ""
set_interface_property rx_clkout PORT_NAME_MAP ""
set_interface_property rx_clkout SVD_ADDRESS_GROUP ""

add_interface_port rx_clkout rx_clkout clk Input NUM_OF_CH

# 
# connection point rx_is_lockedtodata
# 
add_interface rx_is_lockedtodata conduit end
set_interface_property rx_is_lockedtodata associatedClock ""
set_interface_property rx_is_lockedtodata associatedReset ""
set_interface_property rx_is_lockedtodata ENABLED true
set_interface_property rx_is_lockedtodata EXPORT_OF ""
set_interface_property rx_is_lockedtodata PORT_NAME_MAP ""
set_interface_property rx_is_lockedtodata CMSIS_SVD_VARIABLES ""
set_interface_property rx_is_lockedtodata SVD_ADDRESS_GROUP ""

add_interface_port rx_is_lockedtodata rx_is_lockedtodata rx_is_lockedtodata Input NUM_OF_CH



set_module_property ELABORATION_CALLBACK    elaborate_me








proc elaborate_me {}  {


		
  if { [get_parameter_value NUM_OF_CH] >= 1 }  {

		add_interface tx_data_a conduit end
		set_interface_property tx_data_a associatedClock ""
		set_interface_property tx_data_a associatedReset ""
		set_interface_property tx_data_a ENABLED true
		set_interface_property tx_data_a EXPORT_OF ""
		set_interface_property tx_data_a PORT_NAME_MAP ""
		set_interface_property tx_data_a SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_a tx_data_a export Input DATAWIDTH

		add_interface tx_clkout_a conduit end
		set_interface_property tx_clkout_a associatedClock ""
		set_interface_property tx_clkout_a associatedReset ""
		set_interface_property tx_clkout_a ENABLED true
		set_interface_property tx_clkout_a EXPORT_OF ""
		set_interface_property tx_clkout_a PORT_NAME_MAP ""
		set_interface_property tx_clkout_a SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_a tx_clkout_a export Output 1


		
		add_interface rx_data_a conduit end
		set_interface_property rx_data_a associatedClock ""
		set_interface_property rx_data_a associatedReset ""
		set_interface_property rx_data_a ENABLED true
		set_interface_property rx_data_a EXPORT_OF ""
		set_interface_property rx_data_a PORT_NAME_MAP ""
		set_interface_property rx_data_a SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_a rx_data_a export Output DATAWIDTH

		
		add_interface rx_clkout_a conduit end
		set_interface_property rx_clkout_a associatedClock ""
		set_interface_property rx_clkout_a associatedReset ""
		set_interface_property rx_clkout_a ENABLED true
		set_interface_property rx_clkout_a EXPORT_OF ""
		set_interface_property rx_clkout_a PORT_NAME_MAP ""
		set_interface_property rx_clkout_a SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_a rx_clkout_a export Output 1


		add_interface test_reset_n_a reset start
		set_interface_property test_reset_n_a associatedClock ""
		set_interface_property test_reset_n_a associatedDirectReset ""
		set_interface_property test_reset_n_a associatedResetSinks ""
		set_interface_property test_reset_n_a synchronousEdges NONE
		set_interface_property test_reset_n_a ENABLED true
		set_interface_property test_reset_n_a EXPORT_OF ""
		set_interface_property test_reset_n_a PORT_NAME_MAP ""
		set_interface_property test_reset_n_a CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_a SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_a test_reset_n_a reset_n Output 1
		

		add_interface tx_clkout_a_output clock start
		set_interface_property tx_clkout_a_output associatedDirectClock ""
		set_interface_property tx_clkout_a_output clockRate 0
		set_interface_property tx_clkout_a_output clockRateKnown false
		set_interface_property tx_clkout_a_output ENABLED true
		set_interface_property tx_clkout_a_output EXPORT_OF ""
		set_interface_property tx_clkout_a_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_a_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_a_output tx_clkout_a_output clk Output 1
		
		add_interface rx_clkout_a_output clock start
		set_interface_property rx_clkout_a_output associatedDirectClock ""
		set_interface_property rx_clkout_a_output clockRate 0
		set_interface_property rx_clkout_a_output clockRateKnown false
		set_interface_property rx_clkout_a_output ENABLED true
		set_interface_property rx_clkout_a_output EXPORT_OF ""
		set_interface_property rx_clkout_a_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_a_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_a_output rx_clkout_a_output clk Output 1
	}

  if { [get_parameter_value NUM_OF_CH] >= 2 }  {
		add_interface tx_data_b conduit end
		set_interface_property tx_data_b associatedClock ""
		set_interface_property tx_data_b associatedReset ""
		set_interface_property tx_data_b ENABLED true
		set_interface_property tx_data_b EXPORT_OF ""
		set_interface_property tx_data_b PORT_NAME_MAP ""
		set_interface_property tx_data_b SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_b tx_data_b export Input DATAWIDTH

		add_interface tx_clkout_b conduit end
		set_interface_property tx_clkout_b associatedClock ""
		set_interface_property tx_clkout_b associatedReset ""
		set_interface_property tx_clkout_b ENABLED true
		set_interface_property tx_clkout_b EXPORT_OF ""
		set_interface_property tx_clkout_b PORT_NAME_MAP ""
		set_interface_property tx_clkout_b SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_b tx_clkout_b export Output 1


		
		add_interface rx_data_b conduit end
		set_interface_property rx_data_b associatedClock ""
		set_interface_property rx_data_b associatedReset ""
		set_interface_property rx_data_b ENABLED true
		set_interface_property rx_data_b EXPORT_OF ""
		set_interface_property rx_data_b PORT_NAME_MAP ""
		set_interface_property rx_data_b SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_b rx_data_b export Output DATAWIDTH

		add_interface rx_clkout_b conduit end
		set_interface_property rx_clkout_b associatedClock ""
		set_interface_property rx_clkout_b associatedReset ""
		set_interface_property rx_clkout_b ENABLED true
		set_interface_property rx_clkout_b EXPORT_OF ""
		set_interface_property rx_clkout_b PORT_NAME_MAP ""
		set_interface_property rx_clkout_b SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_b rx_clkout_b export Output 1	
		

		add_interface test_reset_n_b reset start
		set_interface_property test_reset_n_b associatedClock ""
		set_interface_property test_reset_n_b associatedDirectReset ""
		set_interface_property test_reset_n_b associatedResetSinks ""
		set_interface_property test_reset_n_b synchronousEdges NONE
		set_interface_property test_reset_n_b ENABLED true
		set_interface_property test_reset_n_b EXPORT_OF ""
		set_interface_property test_reset_n_b PORT_NAME_MAP ""
		set_interface_property test_reset_n_b CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_b SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_b test_reset_n_b reset_n Output 1		
		
		
		add_interface tx_clkout_b_output clock start
		set_interface_property tx_clkout_b_output associatedDirectClock ""
		set_interface_property tx_clkout_b_output clockRate 0
		set_interface_property tx_clkout_b_output clockRateKnown false
		set_interface_property tx_clkout_b_output ENABLED true
		set_interface_property tx_clkout_b_output EXPORT_OF ""
		set_interface_property tx_clkout_b_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_b_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_b_output tx_clkout_b_output clk Output 1
		
		add_interface rx_clkout_b_output clock start
		set_interface_property rx_clkout_b_output associatedDirectClock ""
		set_interface_property rx_clkout_b_output clockRate 0
		set_interface_property rx_clkout_b_output clockRateKnown false
		set_interface_property rx_clkout_b_output ENABLED true
		set_interface_property rx_clkout_b_output EXPORT_OF ""
		set_interface_property rx_clkout_b_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_b_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_b_output rx_clkout_b_output clk Output 1
	}

  if { [get_parameter_value NUM_OF_CH] >= 3 }  {

		add_interface tx_data_c conduit end
		set_interface_property tx_data_c associatedClock ""
		set_interface_property tx_data_c associatedReset ""
		set_interface_property tx_data_c ENABLED true
		set_interface_property tx_data_c EXPORT_OF ""
		set_interface_property tx_data_c PORT_NAME_MAP ""
		set_interface_property tx_data_c SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_c tx_data_c export Input DATAWIDTH

		add_interface tx_clkout_c conduit end
		set_interface_property tx_clkout_c associatedClock ""
		set_interface_property tx_clkout_c associatedReset ""
		set_interface_property tx_clkout_c ENABLED true
		set_interface_property tx_clkout_c EXPORT_OF ""
		set_interface_property tx_clkout_c PORT_NAME_MAP ""
		set_interface_property tx_clkout_c SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_c tx_clkout_c export Output 1


		
		add_interface rx_data_c conduit end
		set_interface_property rx_data_c associatedClock ""
		set_interface_property rx_data_c associatedReset ""
		set_interface_property rx_data_c ENABLED true
		set_interface_property rx_data_c EXPORT_OF ""
		set_interface_property rx_data_c PORT_NAME_MAP ""
		set_interface_property rx_data_c SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_c rx_data_c export Output DATAWIDTH

		add_interface rx_clkout_c conduit end
		set_interface_property rx_clkout_c associatedClock ""
		set_interface_property rx_clkout_c associatedReset ""
		set_interface_property rx_clkout_c ENABLED true
		set_interface_property rx_clkout_c EXPORT_OF ""
		set_interface_property rx_clkout_c PORT_NAME_MAP ""
		set_interface_property rx_clkout_c SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_c rx_clkout_c export Output 1	
		

		
		add_interface test_reset_n_c reset start
		set_interface_property test_reset_n_c associatedClock ""
		set_interface_property test_reset_n_c associatedDirectReset ""
		set_interface_property test_reset_n_c associatedResetSinks ""
		set_interface_property test_reset_n_c synchronousEdges NONE
		set_interface_property test_reset_n_c ENABLED true
		set_interface_property test_reset_n_c EXPORT_OF ""
		set_interface_property test_reset_n_c PORT_NAME_MAP ""
		set_interface_property test_reset_n_c CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_c SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_c test_reset_n_c reset_n Output 1		
		
		
		add_interface tx_clkout_c_output clock start
		set_interface_property tx_clkout_c_output associatedDirectClock ""
		set_interface_property tx_clkout_c_output clockRate 0
		set_interface_property tx_clkout_c_output clockRateKnown false
		set_interface_property tx_clkout_c_output ENABLED true
		set_interface_property tx_clkout_c_output EXPORT_OF ""
		set_interface_property tx_clkout_c_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_c_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_c_output tx_clkout_c_output clk Output 1
		
		add_interface rx_clkout_c_output clock start
		set_interface_property rx_clkout_c_output associatedDirectClock ""
		set_interface_property rx_clkout_c_output clockRate 0
		set_interface_property rx_clkout_c_output clockRateKnown false
		set_interface_property rx_clkout_c_output ENABLED true
		set_interface_property rx_clkout_c_output EXPORT_OF ""
		set_interface_property rx_clkout_c_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_c_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_c_output rx_clkout_c_output clk Output 1
	}

  if { [get_parameter_value NUM_OF_CH] >= 4 }  {
		add_interface tx_data_d conduit end
		set_interface_property tx_data_d associatedClock ""
		set_interface_property tx_data_d associatedReset ""
		set_interface_property tx_data_d ENABLED true
		set_interface_property tx_data_d EXPORT_OF ""
		set_interface_property tx_data_d PORT_NAME_MAP ""
		set_interface_property tx_data_d SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_d tx_data_d export Input DATAWIDTH

		add_interface tx_clkout_d conduit end
		set_interface_property tx_clkout_d associatedClock ""
		set_interface_property tx_clkout_d associatedReset ""
		set_interface_property tx_clkout_d ENABLED true
		set_interface_property tx_clkout_d EXPORT_OF ""
		set_interface_property tx_clkout_d PORT_NAME_MAP ""
		set_interface_property tx_clkout_d SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_d tx_clkout_d export Output 1


		
		add_interface rx_data_d conduit end
		set_interface_property rx_data_d associatedClock ""
		set_interface_property rx_data_d associatedReset ""
		set_interface_property rx_data_d ENABLED true
		set_interface_property rx_data_d EXPORT_OF ""
		set_interface_property rx_data_d PORT_NAME_MAP ""
		set_interface_property rx_data_d SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_d rx_data_d export Output DATAWIDTH

		add_interface rx_clkout_d conduit end
		set_interface_property rx_clkout_d associatedClock ""
		set_interface_property rx_clkout_d associatedReset ""
		set_interface_property rx_clkout_d ENABLED true
		set_interface_property rx_clkout_d EXPORT_OF ""
		set_interface_property rx_clkout_d PORT_NAME_MAP ""
		set_interface_property rx_clkout_d SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_d rx_clkout_d export Output 1	


		
		add_interface test_reset_n_d reset start
		set_interface_property test_reset_n_d associatedClock ""
		set_interface_property test_reset_n_d associatedDirectReset ""
		set_interface_property test_reset_n_d associatedResetSinks ""
		set_interface_property test_reset_n_d synchronousEdges NONE
		set_interface_property test_reset_n_d ENABLED true
		set_interface_property test_reset_n_d EXPORT_OF ""
		set_interface_property test_reset_n_d PORT_NAME_MAP ""
		set_interface_property test_reset_n_d CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_d SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_d test_reset_n_d reset_n Output 1		
		
		
		add_interface tx_clkout_d_output clock start
		set_interface_property tx_clkout_d_output associatedDirectClock ""
		set_interface_property tx_clkout_d_output clockRate 0
		set_interface_property tx_clkout_d_output clockRateKnown false
		set_interface_property tx_clkout_d_output ENABLED true
		set_interface_property tx_clkout_d_output EXPORT_OF ""
		set_interface_property tx_clkout_d_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_d_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_d_output tx_clkout_d_output clk Output 1
		
		add_interface rx_clkout_d_output clock start
		set_interface_property rx_clkout_d_output associatedDirectClock ""
		set_interface_property rx_clkout_d_output clockRate 0
		set_interface_property rx_clkout_d_output clockRateKnown false
		set_interface_property rx_clkout_d_output ENABLED true
		set_interface_property rx_clkout_d_output EXPORT_OF ""
		set_interface_property rx_clkout_d_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_d_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_d_output rx_clkout_d_output clk Output 1
	}



  if { [get_parameter_value NUM_OF_CH] >= 5 }  {
		add_interface tx_data_e conduit end
		set_interface_property tx_data_e associatedClock ""
		set_interface_property tx_data_e associatedReset ""
		set_interface_property tx_data_e ENABLED true
		set_interface_property tx_data_e EXPORT_OF ""
		set_interface_property tx_data_e PORT_NAME_MAP ""
		set_interface_property tx_data_e SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_e tx_data_e export Input DATAWIDTH

		add_interface tx_clkout_e conduit end
		set_interface_property tx_clkout_e associatedClock ""
		set_interface_property tx_clkout_e associatedReset ""
		set_interface_property tx_clkout_e ENABLED true
		set_interface_property tx_clkout_e EXPORT_OF ""
		set_interface_property tx_clkout_e PORT_NAME_MAP ""
		set_interface_property tx_clkout_e SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_e tx_clkout_e export Output 1


		
		add_interface rx_data_e conduit end
		set_interface_property rx_data_e associatedClock ""
		set_interface_property rx_data_e associatedReset ""
		set_interface_property rx_data_e ENABLED true
		set_interface_property rx_data_e EXPORT_OF ""
		set_interface_property rx_data_e PORT_NAME_MAP ""
		set_interface_property rx_data_e SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_e rx_data_e export Output DATAWIDTH

		add_interface rx_clkout_e conduit end
		set_interface_property rx_clkout_e associatedClock ""
		set_interface_property rx_clkout_e associatedReset ""
		set_interface_property rx_clkout_e ENABLED true
		set_interface_property rx_clkout_e EXPORT_OF ""
		set_interface_property rx_clkout_e PORT_NAME_MAP ""
		set_interface_property rx_clkout_e SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_e rx_clkout_e export Output 1


		
		add_interface test_reset_n_e reset start
		set_interface_property test_reset_n_e associatedClock ""
		set_interface_property test_reset_n_e associatedDirectReset ""
		set_interface_property test_reset_n_e associatedResetSinks ""
		set_interface_property test_reset_n_e synchronousEdges NONE
		set_interface_property test_reset_n_e ENABLED true
		set_interface_property test_reset_n_e EXPORT_OF ""
		set_interface_property test_reset_n_e PORT_NAME_MAP ""
		set_interface_property test_reset_n_e CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_e SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_e test_reset_n_e reset_n Output 1		
		
		
		add_interface tx_clkout_e_output clock start
		set_interface_property tx_clkout_e_output associatedDirectClock ""
		set_interface_property tx_clkout_e_output clockRate 0
		set_interface_property tx_clkout_e_output clockRateKnown false
		set_interface_property tx_clkout_e_output ENABLED true
		set_interface_property tx_clkout_e_output EXPORT_OF ""
		set_interface_property tx_clkout_e_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_e_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_e_output tx_clkout_e_output clk Output 1
		
		add_interface rx_clkout_e_output clock start
		set_interface_property rx_clkout_e_output associatedDirectClock ""
		set_interface_property rx_clkout_e_output clockRate 0
		set_interface_property rx_clkout_e_output clockRateKnown false
		set_interface_property rx_clkout_e_output ENABLED true
		set_interface_property rx_clkout_e_output EXPORT_OF ""
		set_interface_property rx_clkout_e_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_e_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_e_output rx_clkout_e_output clk Output 1
	}

	if { [get_parameter_value NUM_OF_CH] >= 6 }  {
		add_interface tx_data_f conduit end
		set_interface_property tx_data_f associatedClock ""
		set_interface_property tx_data_f associatedReset ""
		set_interface_property tx_data_f ENABLED true
		set_interface_property tx_data_f EXPORT_OF ""
		set_interface_property tx_data_f PORT_NAME_MAP ""
		set_interface_property tx_data_f SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_f tx_data_f export Input DATAWIDTH

		add_interface tx_clkout_f conduit end
		set_interface_property tx_clkout_f associatedClock ""
		set_interface_property tx_clkout_f associatedReset ""
		set_interface_property tx_clkout_f ENABLED true
		set_interface_property tx_clkout_f EXPORT_OF ""
		set_interface_property tx_clkout_f PORT_NAME_MAP ""
		set_interface_property tx_clkout_f SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_f tx_clkout_f export Output 1


		
		add_interface rx_data_f conduit end
		set_interface_property rx_data_f associatedClock ""
		set_interface_property rx_data_f associatedReset ""
		set_interface_property rx_data_f ENABLED true
		set_interface_property rx_data_f EXPORT_OF ""
		set_interface_property rx_data_f PORT_NAME_MAP ""
		set_interface_property rx_data_f SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_f rx_data_f export Output DATAWIDTH

		add_interface rx_clkout_f conduit end
		set_interface_property rx_clkout_f associatedClock ""
		set_interface_property rx_clkout_f associatedReset ""
		set_interface_property rx_clkout_f ENABLED true
		set_interface_property rx_clkout_f EXPORT_OF ""
		set_interface_property rx_clkout_f PORT_NAME_MAP ""
		set_interface_property rx_clkout_f SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_f rx_clkout_f export Output 1


		
		add_interface test_reset_n_f reset start
		set_interface_property test_reset_n_f associatedClock ""
		set_interface_property test_reset_n_f associatedDirectReset ""
		set_interface_property test_reset_n_f associatedResetSinks ""
		set_interface_property test_reset_n_f synchronousEdges NONE
		set_interface_property test_reset_n_f ENABLED true
		set_interface_property test_reset_n_f EXPORT_OF ""
		set_interface_property test_reset_n_f PORT_NAME_MAP ""
		set_interface_property test_reset_n_f CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_f SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_f test_reset_n_f reset_n Output 1		
		
		
		add_interface tx_clkout_f_output clock start
		set_interface_property tx_clkout_f_output associatedDirectClock ""
		set_interface_property tx_clkout_f_output clockRate 0
		set_interface_property tx_clkout_f_output clockRateKnown false
		set_interface_property tx_clkout_f_output ENABLED true
		set_interface_property tx_clkout_f_output EXPORT_OF ""
		set_interface_property tx_clkout_f_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_f_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_f_output tx_clkout_f_output clk Output 1
		
		add_interface rx_clkout_f_output clock start
		set_interface_property rx_clkout_f_output associatedDirectClock ""
		set_interface_property rx_clkout_f_output clockRate 0
		set_interface_property rx_clkout_f_output clockRateKnown false
		set_interface_property rx_clkout_f_output ENABLED true
		set_interface_property rx_clkout_f_output EXPORT_OF ""
		set_interface_property rx_clkout_f_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_f_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_f_output rx_clkout_f_output clk Output 1
	}

	if { [get_parameter_value NUM_OF_CH] >= 7 }  {
		add_interface tx_data_g conduit end
		set_interface_property tx_data_g associatedClock ""
		set_interface_property tx_data_g associatedReset ""
		set_interface_property tx_data_g ENABLED true
		set_interface_property tx_data_g EXPORT_OF ""
		set_interface_property tx_data_g PORT_NAME_MAP ""
		set_interface_property tx_data_g SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_g tx_data_g export Input DATAWIDTH

		add_interface tx_clkout_g conduit end
		set_interface_property tx_clkout_g associatedClock ""
		set_interface_property tx_clkout_g associatedReset ""
		set_interface_property tx_clkout_g ENABLED true
		set_interface_property tx_clkout_g EXPORT_OF ""
		set_interface_property tx_clkout_g PORT_NAME_MAP ""
		set_interface_property tx_clkout_g SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_g tx_clkout_g export Output 1


		
		add_interface rx_data_g conduit end
		set_interface_property rx_data_g associatedClock ""
		set_interface_property rx_data_g associatedReset ""
		set_interface_property rx_data_g ENABLED true
		set_interface_property rx_data_g EXPORT_OF ""
		set_interface_property rx_data_g PORT_NAME_MAP ""
		set_interface_property rx_data_g SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_g rx_data_g export Output DATAWIDTH

		add_interface rx_clkout_g conduit end
		set_interface_property rx_clkout_g associatedClock ""
		set_interface_property rx_clkout_g associatedReset ""
		set_interface_property rx_clkout_g ENABLED true
		set_interface_property rx_clkout_g EXPORT_OF ""
		set_interface_property rx_clkout_g PORT_NAME_MAP ""
		set_interface_property rx_clkout_g SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_g rx_clkout_g export Output 1
		


		add_interface test_reset_n_g reset start
		set_interface_property test_reset_n_g associatedClock ""
		set_interface_property test_reset_n_g associatedDirectReset ""
		set_interface_property test_reset_n_g associatedResetSinks ""
		set_interface_property test_reset_n_g synchronousEdges NONE
		set_interface_property test_reset_n_g ENABLED true
		set_interface_property test_reset_n_g EXPORT_OF ""
		set_interface_property test_reset_n_g PORT_NAME_MAP ""
		set_interface_property test_reset_n_g CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_g SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_g test_reset_n_g reset_n Output 1		
		
		
		add_interface tx_clkout_g_output clock start
		set_interface_property tx_clkout_g_output associatedDirectClock ""
		set_interface_property tx_clkout_g_output clockRate 0
		set_interface_property tx_clkout_g_output clockRateKnown false
		set_interface_property tx_clkout_g_output ENABLED true
		set_interface_property tx_clkout_g_output EXPORT_OF ""
		set_interface_property tx_clkout_g_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_g_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_g_output tx_clkout_g_output clk Output 1
		
		add_interface rx_clkout_g_output clock start
		set_interface_property rx_clkout_g_output associatedDirectClock ""
		set_interface_property rx_clkout_g_output clockRate 0
		set_interface_property rx_clkout_g_output clockRateKnown false
		set_interface_property rx_clkout_g_output ENABLED true
		set_interface_property rx_clkout_g_output EXPORT_OF ""
		set_interface_property rx_clkout_g_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_g_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_g_output rx_clkout_g_output clk Output 1
	}

	if { [get_parameter_value NUM_OF_CH] >= 8 }  {
		add_interface tx_data_h conduit end
		set_interface_property tx_data_h associatedClock ""
		set_interface_property tx_data_h associatedReset ""
		set_interface_property tx_data_h ENABLED true
		set_interface_property tx_data_h EXPORT_OF ""
		set_interface_property tx_data_h PORT_NAME_MAP ""
		set_interface_property tx_data_h SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_h tx_data_h export Input DATAWIDTH

		add_interface tx_clkout_h conduit end
		set_interface_property tx_clkout_h associatedClock ""
		set_interface_property tx_clkout_h associatedReset ""
		set_interface_property tx_clkout_h ENABLED true
		set_interface_property tx_clkout_h EXPORT_OF ""
		set_interface_property tx_clkout_h PORT_NAME_MAP ""
		set_interface_property tx_clkout_h SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_h tx_clkout_h export Output 1


		
		add_interface rx_data_h conduit end
		set_interface_property rx_data_h associatedClock ""
		set_interface_property rx_data_h associatedReset ""
		set_interface_property rx_data_h ENABLED true
		set_interface_property rx_data_h EXPORT_OF ""
		set_interface_property rx_data_h PORT_NAME_MAP ""
		set_interface_property rx_data_h SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_h rx_data_h export Output DATAWIDTH

		add_interface rx_clkout_h conduit end
		set_interface_property rx_clkout_h associatedClock ""
		set_interface_property rx_clkout_h associatedReset ""
		set_interface_property rx_clkout_h ENABLED true
		set_interface_property rx_clkout_h EXPORT_OF ""
		set_interface_property rx_clkout_h PORT_NAME_MAP ""
		set_interface_property rx_clkout_h SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_h rx_clkout_h export Output 1

		
		add_interface test_reset_n_h reset start
		set_interface_property test_reset_n_h associatedClock ""
		set_interface_property test_reset_n_h associatedDirectReset ""
		set_interface_property test_reset_n_h associatedResetSinks ""
		set_interface_property test_reset_n_h synchronousEdges NONE
		set_interface_property test_reset_n_h ENABLED true
		set_interface_property test_reset_n_h EXPORT_OF ""
		set_interface_property test_reset_n_h PORT_NAME_MAP ""
		set_interface_property test_reset_n_h CMSIS_SVD_VARIABLES ""
		set_interface_property test_reset_n_h SVD_ADDRESS_GROUP ""

		add_interface_port test_reset_n_h test_reset_n_h reset_n Output 1		
		
		
		add_interface tx_clkout_h_output clock start
		set_interface_property tx_clkout_h_output associatedDirectClock ""
		set_interface_property tx_clkout_h_output clockRate 0
		set_interface_property tx_clkout_h_output clockRateKnown false
		set_interface_property tx_clkout_h_output ENABLED true
		set_interface_property tx_clkout_h_output EXPORT_OF ""
		set_interface_property tx_clkout_h_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_h_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_h_output tx_clkout_h_output clk Output 1
		
		add_interface rx_clkout_h_output clock start
		set_interface_property rx_clkout_h_output associatedDirectClock ""
		set_interface_property rx_clkout_h_output clockRate 0
		set_interface_property rx_clkout_h_output clockRateKnown false
		set_interface_property rx_clkout_h_output ENABLED true
		set_interface_property rx_clkout_h_output EXPORT_OF ""
		set_interface_property rx_clkout_h_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_h_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_h_output rx_clkout_h_output clk Output 1
	}
}









