# TCL File Generated by Component Editor 13.1
# Tue Nov 05 10:53:17 PST 2013
# DO NOT MODIFY


# 
# nativePHY_loopback_cont "nativePHY_loopback_cont" v1.0
#  2013.11.05.10:53:17
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module nativePHY_loopback_cont
# 
set_module_property DESCRIPTION ""
set_module_property NAME nativePHY_loopback_cont
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Devkit_IPs
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME nativePHY_loopback_cont
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nativePHY_loopback_cont
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file nativePHY_loopback_cont.v VERILOG PATH nativePHY_loopback_cont.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL nativePHY_loopback_cont
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file nativePHY_loopback_cont.v VERILOG PATH nativePHY_loopback_cont.v


# 
# parameters
# 
add_parameter NUM_OF_CH INTEGER 1
set_parameter_property NUM_OF_CH DEFAULT_VALUE 1
set_parameter_property NUM_OF_CH DISPLAY_NAME NUM_OF_CH
set_parameter_property NUM_OF_CH TYPE INTEGER
set_parameter_property NUM_OF_CH UNITS None
set_parameter_property NUM_OF_CH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_OF_CH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input 4
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_writedata writedata Input 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

# 
# connection point pll_locked
# 
add_interface pll_locked conduit end
set_interface_property pll_locked associatedClock ""
set_interface_property pll_locked associatedReset ""
set_interface_property pll_locked ENABLED true
set_interface_property pll_locked EXPORT_OF ""
set_interface_property pll_locked PORT_NAME_MAP ""
set_interface_property pll_locked CMSIS_SVD_VARIABLES ""
set_interface_property pll_locked SVD_ADDRESS_GROUP ""

add_interface_port pll_locked pll_locked pll_locked Input NUM_OF_CH

# 
# connection point rx_is_lockedtoref
# 
add_interface rx_is_lockedtoref conduit end
set_interface_property rx_is_lockedtoref associatedClock ""
set_interface_property rx_is_lockedtoref associatedReset ""
set_interface_property rx_is_lockedtoref ENABLED true
set_interface_property rx_is_lockedtoref EXPORT_OF ""
set_interface_property rx_is_lockedtoref PORT_NAME_MAP ""
set_interface_property rx_is_lockedtoref CMSIS_SVD_VARIABLES ""
set_interface_property rx_is_lockedtoref SVD_ADDRESS_GROUP ""

add_interface_port rx_is_lockedtoref rx_is_lockedtoref rx_is_lockedtoref Input NUM_OF_CH


# 
# connection point rx_seriallpbken
# 
add_interface rx_seriallpbken conduit end
set_interface_property rx_seriallpbken associatedClock ""
set_interface_property rx_seriallpbken associatedReset ""
set_interface_property rx_seriallpbken ENABLED true
set_interface_property rx_seriallpbken EXPORT_OF ""
set_interface_property rx_seriallpbken PORT_NAME_MAP ""
set_interface_property rx_seriallpbken CMSIS_SVD_VARIABLES ""
set_interface_property rx_seriallpbken SVD_ADDRESS_GROUP ""

add_interface_port rx_seriallpbken rx_seriallpbken rx_seriallpbken Output NUM_OF_CH


# 
# connection point rx_seriallpbken_mon
# 
add_interface rx_seriallpbken_mon conduit end
set_interface_property rx_seriallpbken_mon associatedClock clock
set_interface_property rx_seriallpbken_mon associatedReset ""
set_interface_property rx_seriallpbken_mon ENABLED true
set_interface_property rx_seriallpbken_mon EXPORT_OF ""
set_interface_property rx_seriallpbken_mon PORT_NAME_MAP ""
set_interface_property rx_seriallpbken_mon CMSIS_SVD_VARIABLES ""
set_interface_property rx_seriallpbken_mon SVD_ADDRESS_GROUP ""

add_interface_port rx_seriallpbken_mon rx_seriallpbken_mon export Output NUM_OF_CH

