	xcvr_test_system u0 (
		.clk_50_clk                                                                  (_connected_to_clk_50_clk_),                                                                  //   input,   width = 1,                                                               clk_50.clk
		.reset_50_reset_n                                                            (_connected_to_reset_50_reset_n_),                                                            //   input,   width = 1,                                                             reset_50.reset_n
		.mm_bridge_0_s0_waitrequest                                                  (_connected_to_mm_bridge_0_s0_waitrequest_),                                                  //  output,   width = 1,                                                       mm_bridge_0_s0.waitrequest
		.mm_bridge_0_s0_readdata                                                     (_connected_to_mm_bridge_0_s0_readdata_),                                                     //  output,  width = 32,                                                                     .readdata
		.mm_bridge_0_s0_readdatavalid                                                (_connected_to_mm_bridge_0_s0_readdatavalid_),                                                //  output,   width = 1,                                                                     .readdatavalid
		.mm_bridge_0_s0_burstcount                                                   (_connected_to_mm_bridge_0_s0_burstcount_),                                                   //   input,   width = 1,                                                                     .burstcount
		.mm_bridge_0_s0_writedata                                                    (_connected_to_mm_bridge_0_s0_writedata_),                                                    //   input,  width = 32,                                                                     .writedata
		.mm_bridge_0_s0_address                                                      (_connected_to_mm_bridge_0_s0_address_),                                                      //   input,  width = 13,                                                                     .address
		.mm_bridge_0_s0_write                                                        (_connected_to_mm_bridge_0_s0_write_),                                                        //   input,   width = 1,                                                                     .write
		.mm_bridge_0_s0_read                                                         (_connected_to_mm_bridge_0_s0_read_),                                                         //   input,   width = 1,                                                                     .read
		.mm_bridge_0_s0_byteenable                                                   (_connected_to_mm_bridge_0_s0_byteenable_),                                                   //   input,   width = 4,                                                                     .byteenable
		.mm_bridge_0_s0_debugaccess                                                  (_connected_to_mm_bridge_0_s0_debugaccess_),                                                  //   input,   width = 1,                                                                     .debugaccess
		.xcvr_tx_rx_clkout2_converter_0_rx_clkout2_clk                               (_connected_to_xcvr_tx_rx_clkout2_converter_0_rx_clkout2_clk_),                               //   input,   width = 1,                            xcvr_tx_rx_clkout2_converter_0_rx_clkout2.clk
		.xcvr_tx_rx_clkout2_converter_0_tx_clkout2_clk                               (_connected_to_xcvr_tx_rx_clkout2_converter_0_tx_clkout2_clk_),                               //   input,   width = 1,                            xcvr_tx_rx_clkout2_converter_0_tx_clkout2.clk
		.xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in_export        (_connected_to_xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in_export_),        //   input,  width = 64,        xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in.export
		.xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in_clk_export    (_connected_to_xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in_clk_export_),    //   input,   width = 1,    xcvr_user_rx_fifo_converter_0_data_pattern_checker_pattern_in_clk.export
		.xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out_export     (_connected_to_xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out_export_),     //  output,  width = 64,     xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out.export
		.xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out_clk_export (_connected_to_xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out_clk_export_)  //   input,   width = 1, xcvr_user_tx_fifo_converter_0_data_pattern_generator_pattern_out_clk.export
	);

