# TCL File Generated by Component Editor 13.0
# Wed May 01 20:29:02 PDT 2013
# DO NOT MODIFY


# 
# master_driver_com "master_driver_com" v1.0
#  2013.05.01.20:29:02
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module master_driver_com
# 
set_module_property DESCRIPTION ""
set_module_property NAME master_driver_com
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Devkit_IPs
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME master_driver_com
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL master_driver_com
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file master_driver_com.v VERILOG PATH master_driver_com.v


# 
# parameters
# 
add_parameter CHECKER_BASE STD_LOGIC_VECTOR 32
set_parameter_property CHECKER_BASE DEFAULT_VALUE 32
set_parameter_property CHECKER_BASE DISPLAY_NAME CHECKER_BASE
set_parameter_property CHECKER_BASE WIDTH 32
set_parameter_property CHECKER_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property CHECKER_BASE UNITS None
set_parameter_property CHECKER_BASE ALLOWED_RANGES 0:1879048192
set_parameter_property CHECKER_BASE HDL_PARAMETER true
add_parameter GENERATOR_BASE STD_LOGIC_VECTOR 0 ""
set_parameter_property GENERATOR_BASE DEFAULT_VALUE 0
set_parameter_property GENERATOR_BASE DISPLAY_NAME GENERATOR_BASE
set_parameter_property GENERATOR_BASE WIDTH 32
set_parameter_property GENERATOR_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property GENERATOR_BASE UNITS None
set_parameter_property GENERATOR_BASE DESCRIPTION ""
set_parameter_property GENERATOR_BASE HDL_PARAMETER true
add_parameter TIMER_BASE STD_LOGIC_VECTOR 256
set_parameter_property TIMER_BASE DEFAULT_VALUE 256
set_parameter_property TIMER_BASE DISPLAY_NAME TIMER_BASE
set_parameter_property TIMER_BASE WIDTH 32
set_parameter_property TIMER_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property TIMER_BASE UNITS None
set_parameter_property TIMER_BASE ALLOWED_RANGES 0:1879048192
set_parameter_property TIMER_BASE HDL_PARAMETER true
add_parameter FREQ_BASE STD_LOGIC_VECTOR 512
set_parameter_property FREQ_BASE DEFAULT_VALUE 512
set_parameter_property FREQ_BASE DISPLAY_NAME FREQ_BASE
set_parameter_property FREQ_BASE WIDTH 32
set_parameter_property FREQ_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property FREQ_BASE UNITS None
set_parameter_property FREQ_BASE ALLOWED_RANGES 0:1879048192
set_parameter_property FREQ_BASE HDL_PARAMETER true
add_parameter DESERIALIZATION_FACTOR STD_LOGIC_VECTOR 8
set_parameter_property DESERIALIZATION_FACTOR DEFAULT_VALUE 8
set_parameter_property DESERIALIZATION_FACTOR DISPLAY_NAME DESERIALIZATION_FACTOR
set_parameter_property DESERIALIZATION_FACTOR WIDTH 32
set_parameter_property DESERIALIZATION_FACTOR TYPE STD_LOGIC_VECTOR
set_parameter_property DESERIALIZATION_FACTOR UNITS None
set_parameter_property DESERIALIZATION_FACTOR ALLOWED_RANGES 0:1879048192
set_parameter_property DESERIALIZATION_FACTOR HDL_PARAMETER true
add_parameter NUM_OF_CH STD_LOGIC_VECTOR 16
set_parameter_property NUM_OF_CH DEFAULT_VALUE 16
set_parameter_property NUM_OF_CH DISPLAY_NAME NUM_OF_CH
set_parameter_property NUM_OF_CH WIDTH 32
set_parameter_property NUM_OF_CH TYPE STD_LOGIC_VECTOR
set_parameter_property NUM_OF_CH UNITS None
set_parameter_property NUM_OF_CH ALLOWED_RANGES 0:1879048192
set_parameter_property NUM_OF_CH HDL_PARAMETER true
add_parameter ENABLE_PER_INFO INTEGER 1 "Enable Performance Information Calclation in HDL"
set_parameter_property ENABLE_PER_INFO DEFAULT_VALUE 1
set_parameter_property ENABLE_PER_INFO DISPLAY_NAME "Enable Performance Calculation in HDL"
set_parameter_property ENABLE_PER_INFO TYPE INTEGER
set_parameter_property ENABLE_PER_INFO UNITS None
set_parameter_property ENABLE_PER_INFO ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_PER_INFO DESCRIPTION "Enable Performance Information Calclation in HDL"
set_parameter_property ENABLE_PER_INFO DISPLAY_HINT boolean
set_parameter_property ENABLE_PER_INFO HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "Performance Calculate Options" GROUP ""


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_wen write_n Output 1
add_interface_port avalon_master master_oen read_n Output 1
add_interface_port avalon_master master_be byteenable Output 4
add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_wdata writedata Output 32
add_interface_port avalon_master master_rdata readdata Input 32
add_interface_port avalon_master readdatavalid_in readdatavalid Input 1
add_interface_port avalon_master waitrequest_in waitrequest Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_read read Input 1
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_address address Input 4
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end lock export Input 1
add_interface_port conduit_end error_mon export Output 1
add_interface_port conduit_end status_mon export Output 1

