// xcvr_test_system_data_pattern_generator_0_data_pattern_generator_10_utzxrya.v

// This file was auto-generated from data_pattern_generator_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module xcvr_test_system_data_pattern_generator_0_data_pattern_generator_10_utzxrya #(
		parameter ST_DATA_W            = 128,
		parameter BYPASS_ENABLED       = 0,
		parameter AVALON_ENABLED       = 0,
		parameter CROSS_CLK_SYNC_DEPTH = 4
	) (
		input  wire         csr_clk_clk,                    //                 csr_clk.clk
		input  wire         reset_reset,                    //                   reset.reset
		input  wire [2:0]   csr_slave_address,              //               csr_slave.address
		input  wire         csr_slave_write,                //                        .write
		input  wire         csr_slave_read,                 //                        .read
		input  wire [3:0]   csr_slave_byteenable,           //                        .byteenable
		input  wire [31:0]  csr_slave_writedata,            //                        .writedata
		output wire [31:0]  csr_slave_readdata,             //                        .readdata
		input  wire         conduit_pattern_out_clk_export, // conduit_pattern_out_clk.export
		output wire [127:0] aso_data                        //     conduit_pattern_out.export
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (ST_DATA_W != 128)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					st_data_w_check ( .error(1'b1) );
		end
		if (BYPASS_ENABLED != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bypass_enabled_check ( .error(1'b1) );
		end
		if (AVALON_ENABLED != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					avalon_enabled_check ( .error(1'b1) );
		end
		if (CROSS_CLK_SYNC_DEPTH != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cross_clk_sync_depth_check ( .error(1'b1) );
		end
	endgenerate

	data_pattern_generator #(
		.ST_DATA_W          (128),
		.BYPASS_ENABLED     (0),
		.AVALON_ENABLED     (0),
		.FREQ_CNTER_ENABLED (0)
	) data_pattern_generator (
		.avs_clk        (csr_clk_clk),                    //   input,    width = 1,                 csr_clk.clk
		.reset          (reset_reset),                    //   input,    width = 1,           csr_clk_reset.reset
		.avs_address    (csr_slave_address),              //   input,    width = 3,               csr_slave.address
		.avs_write      (csr_slave_write),                //   input,    width = 1,                        .write
		.avs_read       (csr_slave_read),                 //   input,    width = 1,                        .read
		.avs_byteenable (csr_slave_byteenable),           //   input,    width = 4,                        .byteenable
		.avs_writedata  (csr_slave_writedata),            //   input,   width = 32,                        .writedata
		.avs_readdata   (csr_slave_readdata),             //  output,   width = 32,                        .readdata
		.aso_clk        (conduit_pattern_out_clk_export), //   input,    width = 1, conduit_pattern_out_clk.export
		.aso_data       (aso_data)                        //  output,  width = 128,     conduit_pattern_out.export
	);

endmodule
