// xcvr_test_system_xcvr_tx_rx_clkout2_converter_0.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module xcvr_test_system_xcvr_tx_rx_clkout2_converter_0 (
		input  wire  rx_clkout2,        //        rx_clkout2.clk
		output wire  rx_clkout2_a,      //      rx_clkout2_a.export
		output wire  rx_clkout2_b,      //      rx_clkout2_b.export
		input  wire  tx_clkout2,        //        tx_clkout2.clk
		output wire  tx_clkout2_a,      //      tx_clkout2_a.export
		output wire  tx_clkout2_b,      //      tx_clkout2_b.export
		output wire  tx_clkout2_sample  // tx_clkout2_sample.clk
	);

	xcvr_tx_rx_clkout2_converter xcvr_test_system_xcvr_tx_rx_clkout2_converter_0 (
		.rx_clkout2        (rx_clkout2),        //   input,  width = 1,        rx_clkout2.clk
		.rx_clkout2_a      (rx_clkout2_a),      //  output,  width = 1,      rx_clkout2_a.export
		.rx_clkout2_b      (rx_clkout2_b),      //  output,  width = 1,      rx_clkout2_b.export
		.tx_clkout2        (tx_clkout2),        //   input,  width = 1,        tx_clkout2.clk
		.tx_clkout2_a      (tx_clkout2_a),      //  output,  width = 1,      tx_clkout2_a.export
		.tx_clkout2_b      (tx_clkout2_b),      //  output,  width = 1,      tx_clkout2_b.export
		.tx_clkout2_sample (tx_clkout2_sample)  //  output,  width = 1, tx_clkout2_sample.clk
	);

endmodule
