// xcvr_test_system_freq_counter_0.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module xcvr_test_system_freq_counter_0 (
		input  wire        reset_n,      //        reset.reset_n
		input  wire        clk,          //        clock.clk
		input  wire [3:0]  csr_address,  //          csr.address
		input  wire        csr_read,     //             .read
		output wire [31:0] csr_readdata, //             .readdata
		input  wire        sample_clk    // sample_clock.clk
	);

	freq_counter #(
		.SYSTEM_CLK_FREQ_PICO_SEC (20000)
	) freq_counter_0 (
		.reset_n      (reset_n),      //   input,   width = 1,        reset.reset_n
		.clk          (clk),          //   input,   width = 1,        clock.clk
		.csr_address  (csr_address),  //   input,   width = 4,          csr.address
		.csr_read     (csr_read),     //   input,   width = 1,             .read
		.csr_readdata (csr_readdata), //  output,  width = 32,             .readdata
		.sample_clk   (sample_clk)    //   input,   width = 1, sample_clock.clk
	);

endmodule
